### ISSUE TITLE
Edit: Inline oder Modal

### ISSUE THREAD

**Issue by hirbod** [FriendsOfREDAXO/frontend_edit#2]
Der Edit Button führt aktuell nur zurück ins Backend und öffnet die Editieransicht des entsprechenden Slice. Die Umsetzung von Inline-Edit erscheint mir als praktisch unmöglich, wenn dazu REDAXO EPs benutzt werden. Falls das irgendwann ermöglicht werden soll, muss die Frontend-Ausgabe durch einen eigenen Parser geroutet werden. Ich finde den Aufwand für den Nutzen zu groß, da zu viele Wege abgedeckt werden müssen.

Besser: Der Link öffnet ein Modal direkt im Frontend, wo nur der entsprechende Part in der Editieransicht geöffnet ist. Nach dem Speichern wird das Modal geschlossen und ein Reload im Frontend abgesetzt. Das sollte sich ziemlich einfach umsetzen lassen.

Das hier wird unser Diskussionsthread.

**Comment by skerbis** [comment]
Alternative: eim Split-View: links die Blöcke / Slices, rechts die gerade bearbeitete Website mit Umschaltung zwischen Desktop und Mobilansicht. Wird ein Slice gespeichert aktualisiert sich die Frontendview.  Also eine Art Mischform aus Backend und Frontend.

**Comment by skerbis** [comment]
Vielleicht wie bei sulu.io
![bildschirmfoto 2017-03-18 um 17 05 56](https://cloud.githubusercontent.com/assets/791247/24073782/472f3bd4-0bfd-11e7-8775-ab80e0d97c4f.png)

**Comment by cukabeka** [comment]
Oder bei Jimdo 

![image](https://cloud.githubusercontent.com/assets/688274/24111063/8e522bb8-0d95-11e7-8133-eebd278df2db.png)

**Comment by hirbod** [comment]
<img width="1433" alt="bildschirmfoto 2017-03-21 um 05 56 41" src="https://cloud.githubusercontent.com/assets/504909/24133186/33478932-0dfb-11e7-8895-01a56a50b124.png">

Die ersten Tests funktionieren schon ganz gut. Damit aber die Skalierung (media-queries) funktioniert, muss ich das ganze mittels iframes umsetzen (sowohl das Frontend, als auch das Backend)

Beim Edit-Button generiere ich also 2 Iframes, die jeweils über die Seite gelegt werden. Ich muss dann noch die Positionen syncen und mittels postMessage unter den iframes kommunizieren. Dafür brauch ich dann noch Listener und Helper im Backend und Frontend. Mal sehen, wie gut das funktionieren wird.

**Comment by skerbis** [comment]
Die hier gezeigte Darstellung ist aktuell ohne Iframes? Wie?

**Comment by hirbod** [comment]
Welche? Meine? Ist mit

**Comment by skerbis** [comment]
Dann habe ich den Text falsch verstanden

**Comment by hirbod** [comment]
Ersetze "muss" zu "musste" dann ist der Kontext klar. Hab scheisse geschrieben :F
