### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by hirbod** [FriendsOfREDAXO/frontend_edit#5]
Die Toolbar ist aktuell noch Nackt. Rein soll:

* Logo
* Reload-Button
* Aktuellen Artikel-Cache leeren
* Lang-Switcher?
* Gesamten Cache leeren (Admins-only)?

**Comment by olien** [comment]
Ich finde Leiste sollte unbedingt ein und ausschaltbar sein. 

Sofern ich mit WP arbeite gucke ich, dass ich deren Admin Leiste auch immer komplett ausschalte. Stört mich extrem im Frontend bei der Entwicklung.

Lang Switcher sollte ja auf jeder mehrsprachigen Webseite im Frontend möglich sein - oder nicht? Die Funktion finde ich hier nicht notwendig. Ein Logo auch nicht :-)

Ich hab mal was gekritzelt:

Klein und unaufällig. 1. Icon blendet die Edit Buttons ein und aus. 2. Button öffnet die Einstellungen.

![eingeklappt](https://cloud.githubusercontent.com/assets/330516/23986744/0aecc11a-0a26-11e7-8d00-73188f6833f7.png)
![ausgeklappt](https://cloud.githubusercontent.com/assets/330516/23986748/0e36c9d8-0a26-11e7-8570-ac041463fef6.png)

P.S.: Guck dir doch mal das Addon headsupgrid an...

**Comment by skerbis** [comment]
Warum eine Leiste, mit Logo etc. ? Ich habe immer ein kleines schwebenden Div. 
Das zeigt auch immer nur die Funktionen an die gerade möglich sind. 
Es gibt echt Redakteure, die einen sonst fragen ob der Balken oben dazu gehört. 
![bildschirmfoto 2017-03-16 um 14 41 17](https://cloud.githubusercontent.com/assets/791247/23998815/a20ea628-0a56-11e7-891e-4574ba4e869f.png)

**Comment by hirbod** [comment]
Ich hab mich einfach nur von Wordpress inspirieren lassen. Logo etc genau deswegen, damit es keine Rückfragen von Kunden gibt. Das hier ist alles nicht in Stein gemeißelt, ich möchte ja, das ihr alle Ideen einbringt und wir das optimieren

**Comment by skerbis** [comment]
Eine Leiste stört das Gesamtbild der Website, finde ich. Ein ausblendbares schwebendes Element, würde ich favorisieren.

**Comment by hirbod** [comment]
ich finde @olien vorschlag schon mal gar nicht verkehrt, würde dann ja auch so in deine Richtung gehen @skerbis

**Comment by cukabeka** [comment]
Ich fände eine Auswahl gut. Ich mag die Leiste wie in WP, kann aber verstehen, dass es in anderen Szenarien nicht so gut passt.

**Comment by cukabeka** [comment]
+ die Metadaten direkt als Ändern-Link mit in die Toolbar

**Comment by skerbis** [comment]
@cukabeka sehe ich als optional an
