### ISSUE TITLE
Verlinkung funktioniert nicht.

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/frontend_edit#6]
Wenn ich auf der Seite "Kontakt" einen Slice Edit Button anklicke wird auf 

```abc.tld/kontakt.html#edit```

verlinkt. 
Getestet mit zwei Installationen (aktuelle Redaxo Version)

LG
Oliver

**Comment by hirbod** [comment]
Dann hast du wohl nicht gelesen..

**Comment by olien** [comment]
Ups. Sorry. Ich klicke immer schneller als ich lese :-))
