### ISSUE TITLE
Toolbar erscheint nicht

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/frontend_edit#8]
Konnte hier leider noch nicht testen, da ich die Toolbar schlicht nicht sehe. Getestet mit verschiedenen Templates. 
Muss ich das irgendwo/irgendwie aktivieren, dass die überhaupt ausgegeben wird?

**Comment by hirbod** [comment]
Addon muss aktiviert sein und du musst als Admin im Backend einloggt sein, aber die Toolbar ist noch ohne Funktion. Das ganze ist ein riesiger, roher "Anfangsbaukasten"
